eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka"
server:
  port: 0
spring:
  application:
    name: ideaservice
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=projectservice
    username: postgres
    password: rootaye2
    driver-class-name: org.postgresql.Driver
grpc:
  client:
    address: "discovery:///userservice"
    enable-keep-alive: true
    keep-alive-without-calls: true
    negotiation-type: plaintext
  server:
    port: 0
